coverage:
    status:
        project:
            default:
                target: 85%
                flags:
                    - LWC
                    - Apex
            LWC:
                target: 85%
                flags:
                    - LWC
            Apex:
                target: 95%
                flags:
                    - Apex
        patch: off
ignore:
    - 'src-sample/**'
